### ISSUE TITLE
Support uploading files

### ISSUE THREAD

**Issue by hausen1012** [linuxserver/docker-wireshark#18]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

 uploading files

### Reason for change

Easy to operate on the interface, otherwise it is necessary to copy files to the host

**Comment by aptalca** [comment]
Left side menu opens a file browser

**Comment by hausen1012** [comment]
> Left side menu opens a file browser

thank you
But I don't see a place on the left where I can upload files on my local computer. Can you tell me for screenshots or other means

**Comment by aptalca** [comment]
when you open the left side menu, you'll see the filing cabinet icon at the top middle of the screen next to the speaker icon for enabling audio

**Comment by hausen1012** [comment]
Oh, I see it. Thank you
