### ISSUE TITLE
Network Host: Change Port

### ISSUE THREAD

**Issue by djarbz** [linuxserver/docker-wireshark#7]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Create an environmental variable to specify the webserver port when using host network mode.

------------------------------

## Desired Behavior

On run, pass a `-e PORT=8000` and the webserver will listen on port `8000` rather than `3000`.
## Current Behavior

No option to change the listening port and container will not run in Host mode if something else is listening on port `3000`.
## Alternatives Considered

I could change other software or container's ports, but not all other containers support this.
I would also prefer to keep all of my web ports in the `8000` range.

**Comment by thedanbob** [comment]
It looks like the web functionality comes from [this application](https://github.com/linuxserver/gclient/blob/master/README.md). I can confirm the listen port can be changed with the CUSTOM_PORT envvar.

**Comment by rhuitl** [comment]
Thanks @thedanbob for figuring this out, it worked for me. It would be nice to mention this environment variable in the README!

**Comment by djarbz** [comment]
Sorry for the late reply, thanks for letting us know!
As rhuitl mentioned, this would be great to add to the README!
